# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fhi_3zUj5ZhGyJOQ2UbDnWfl6SrC7SRs

Project Title: Restaurant Tipping Analysis & Visualization

Author: Anushka Bhagra
Date: April 10, 2026
Goal: To explore spending patterns, tipping behavior, and correlation factors using the Seaborn tips dataset.

Task 1: Spending Distribution (Saturday vs. Sunday)
In this section, I use a Kernel Density Estimate (KDE) plot to compare how much customers spend on Saturdays versus Sundays. This helps identify which weekend day typically sees higher-value bills.

Key Insight: Look for the peak of the curve to see the most common "Total Bill" amount for each day.
"""

import seaborn as sns
import matplotlib.pyplot as plt

# 1. Load data
tips = sns.load_dataset("tips")
plt.figure(figsize=(10,8))
# 2. Filter logic (Use the correct column: 'day')
# We use 'Sat'/'Sun' because the dataset uses abbreviations
weekend_data = tips[tips['day'].isin(['Sat', 'Sun'])]
# 3. The Plot
# hue='day' ensures we compare the right categories
sns.kdeplot(data = weekend_data, x ='total_bill', hue = 'day', fill = True, palette = 'viridis', hue_order=['Sat','Sun'])
plt.title("comapring spending on: saturday vs sunday")
sns.despine() # This removes the top and right borders
plt.show()

"""Task 2: Regression Analysis by Table Size
Here, I compare the relationship between the total_bill and the tip for two specific groups: small tables (Size 2) and large tables (Size 4). I use regplot to show the "trend line" of how tips increase as the bill grows.
"""

tips = sns.load_dataset("tips")
sns.set_theme(style="ticks")
plt.figure(figsize=(12,8))
plt.subplot(1,2,1)
size_2_data = tips[tips['size'] == 2]
sns.regplot(data = size_2_data, x ="total_bill", y = 'tip', color='orange')
plt.title('total_bill vs tips')
sns.despine()
plt.subplot(1,2,2)
size_4_data = tips[tips['size']==4]
sns.regplot(data = size_4_data, x = "total_bill", y = 'tip', color ='teal')
sns.despine()
plt.tight_layout()
plt.show()

"""Task 3: Correlation Heatmap (Non-Smokers)
This Heatmap visualizes the correlation matrix for non-smoking customers. It allows us to see at a glance how variables like total_bill, tip, and size relate to one another numerically.
"""

plt.figure(figsize=(10,6))
non_smoker_data = tips[tips['smoker']== 'No']
corr_matrix = non_smoker_data.corr(numeric_only=True)
sns.heatmap(data=corr_matrix, annot=True, cmap="YlGnBu")
plt.title("Correlation Matrix (Non-Smokers)")
plt.show()

"""Task 4: Bin Size Impact (2D Histogram)
I am comparing two different "Bin" settings (5 vs. 50) to demonstrate how the granularity of a histogram changes our perception of the data.

Wide Bins (5): Shows the "Big Picture" trend.

Narrow Bins (50): Shows the "Fine Detail" and specific gaps in the data.
"""

tips = sns.load_dataset("tips")
sns.set_theme(style='darkgrid')
plt.figure(figsize=(10,9))
plt.subplot(2,1,1)
sns.histplot(data = tips,x = "total_bill", y = 'tip', bins = 5, color = 'skyblue')
plt.title("Wide Bins(5): The Big Picture")
plt.subplot(2,1,2)
sns.histplot(data = tips, x = 'total_bill', y = 'tip', bins = 50, color = 'salmon')
plt.title('Narrow Bins(50): The Fine Detail')
plt.tight_layout()
plt.show()

"""Task 5: Time-Based Density for Large Tables
This analysis focuses specifically on larger groups (Tables > 2) to see if their spending habits differ between Lunch and Dinner. I used a thicker linewidth to make the comparison clearer.
"""

tips = sns.load_dataset("tips")
table_data = tips[tips['size'] > 2]
plt.figure(figsize=(10,8))
sns.kdeplot(data = table_data, x = 'total_bill', hue = 'time', palette = 'coolwarm', linewidth = 3, fill = True)
plt.title("total_bill vs time")
plt.show()

"""Task 6: The Multi-Plot Dashboard
This 4-panel dashboard provides a comprehensive overview of the dataset in one view:

1.Histogram: Distribution of bills.

2.Scatterplot: Relationship between bill and tip by day.

3.Boxplot: The "spread" and outliers of bills per day.

4.Barplot: Average tip amount per day.
"""

tips = sns.load_dataset("tips")
plt.figure(figsize=(10,8))
plt.subplot(2,2,1)
sns.histplot(data = tips, x = 'total_bill', kde = True, color = 'skyblue')
plt.title('total_bill')
plt.subplot(2,2,2)
sns.scatterplot(data = tips, x = 'total_bill', y ='tip', hue="day", color = 'salmon')
plt.title('total_bill vs tip')
plt.subplot(2,2,3)
sns.boxplot(data = tips, x = 'total_bill', y ='day', color = 'green')
plt.title('total_bill vs day')
plt.subplot(2,2,4)
sns.barplot(data = tips, x = 'tip', y = 'day', palette = 'magma')
plt.title('tip vs day')
plt.tight_layout()
plt.show()
#

"""Task 7: Tip Distribution (Gender & Smoker Status)
Using a Violin Plot with a split=True parameter, I can compare the tipping density of male vs. female customers while also seeing how smoking habits influence those numbers.
"""

tips = sns.load_dataset("tips")
plt.figure(figsize=(10,8))
sns.violinplot(data = tips , x = 'sex', y = 'tip', hue = 'smoker', split=True, palette= 'magma')
plt.title('tip vs sex')
plt.show()
#

"""Task 8: Feature Engineering - Tip Percentage
Instead of looking at the raw tip amount, I created a new calculated column: tip_pct (Tip divided by Total Bill). This gives a fairer view of how generous customers are regardless of their bill size.
"""

tips = sns.load_dataset("tips")
plt.figure(figsize=(10,8))
tips['tip_pct'] = (tips['tip'] / tips['total_bill']) * 100
sns.kdeplot(data = tips, x = 'tip_pct', fill=True, color = 'salmon')
plt.title('tip percentage distribution')
plt.xlabel('tip percentage')
sns.despine()
plt.show()