# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i-vq6JkrPTHF4mXT7ZbQoUFWNF0TOQhs
"""

"""
BIOSTATISTICS VISUALIZATION SUITE
Focus: Density Estimation, Correlation, and Distribution Analysis
"""
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# 1. Setup Theme
# 'ticks' or 'whitegrid' are great for professional looking plots
sns.set_theme(style="ticks")
# ==========================================
# 1. KERNEL DENSITY ESTIMATION (KDE)
# Wisdom: Comparing probability distributions across different groups.
# In research, this is used to compare drug response across two days.
# =========================================
# 2. Load the Dataset
tips = sns.load_dataset("tips")

plt.figure(figsize=(10,7))
# Filtering for high-value records (Tips > 5) on specific days
filtering_data = tips[tips['day'].isin(["Fri" ,"Sat"]) & (tips['tip'] > 5)]
sns.kdeplot(data = filtering_data, x = 'total_bill',hue ='day', fill = True, palette = 'rocket', hue_order=['Fri','Sat'])
plt.title('Comparing Bills on: Friday and Saturday')
sns.despine()
plt.show()

# ==========================================
# 2. MULTIVARIATE SCATTER PLOT
# Wisdom: Visualizing three dimensions (X, Y, and Size).
# Used for relating 'Concentration' vs 'Absorption' weighted by 'Molecular Size'.
# ==========================================
plt.figure(figsize=(10,9))
filtering_data = tips[tips['time']=='Lunch']
sns.scatterplot(data = filtering_data, x = 'total_bill', y = 'tip', size = 'size', alpha = 0.5, color = "teal")
plt.title('For Lunch how Total_bill and Tips are related')
sns.despine()
plt.show()

# ==========================================
# 3. COMPOSITE DISTRIBUTION (SUBPLOTS)
# Wisdom: Viewing summary statistics (Boxplot) alongside raw frequency (Histogram).
# Essential for spotting 'Outliers' in lab readings.
# ==========================================
plt.figure(figsize=(10,10))
plt.subplot(2,1,1)
filtering_data = tips[tips['day'] == 'Sun']
sns.boxplot(data = filtering_data, x = 'day', y = 'total_bill', palette = "magma")
plt.title("Total Bill on Sunday")
sns.despine()
plt.subplot(2,1,2)
sns.histplot(data = filtering_data, x = 'total_bill', bins = 20, kde = True,color = 'teal')
plt.title('Total Bill Distribution')
sns.despine()
plt.tight_layout()

plt.show()