# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11TGcGemxqJ_837O6Q3cqoDacfVAdqYH9
"""

"""
PHARMACODYNAMIC DOCKING & CONFIDENCE INTERVAL MAPPING - DAY 18
Focus: Binding Affinity Distribution (kcal/mol), Confidence Score Correlation, and Mean Inhibition CI
Project: Molecular Docking Analysis of Piperaceae Phytochemicals against Inflammatory Targets
"""
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

np.random.seed(42)
# ==========================================
# SECTION 1: MOLECULAR DOCKING DATASET
# ==========================================
genes = ['AKT1', 'TNF', 'IL6', 'PTGS2', 'CASP3', 'VEGFA', 'STAT3']
phytochemicals = ['Piperine', 'Piperlongumine', 'Sylvatin', 'Pippali']

data = {
    'Gene': np.random.choice(genes, 150),
    'Compound': np.random.choice(phytochemicals, 150),
    'Binding_Affinity': np.random.uniform(-10.5, -4.0, 150), # kcal/mol
    'Lipinski_Rule': np.random.choice(['Pass', 'Fail'], 150, p=[0.8, 0.2]),
    'Confidence_Score': np.random.uniform(0.5, 0.99, 150)
}
df_docking = pd.DataFrame(data)

# ==========================================
# SECTION 2: LIGAND-RECEPTOR FREQUENCY
# ==========================================

# 2.1 Occurrence Density by Binding Intensity
plt.figure(figsize=(10,9))
sns.countplot(data = df_docking, x = "Compound", hue = "Binding_Affinity", palette= "magma")
plt.title("occurrences of each compound")
sns.despine()
plt.show()

# 2.2 Global Affinity Distribution: Histogram Analysis
plt.figure(figsize=(10,8))
sns.histplot(data = df_docking, x = "Binding_Affinity", hue = "Compound", palette= "magma")
plt.title("Binding affinity of each compound")
sns.despine()
plt.show()

# ================= =========================
# SECTION 3: STATISTICAL RANGE & CORRELATION
# ==========================================

# 3.1 Comparative Potency: Boxplot Analysis of Binding Energy
# Identifying outliers and interquartile ranges for the 4 phytochemicals
plt.title("Binding affinity of each compound")
sns.boxplot(data = df_docking, x = "Compound", y = "Binding_Affinity", palette= "magma")
plt.title("Binding affinity of each compound")
sns.despine()
plt.show()

# 3.2 Reliability Mapping: Affinity vs. Simulation Confidence Score
plt.figure(figsize=(10,8))
sns.scatterplot(data = df_docking, x = "Binding_Affinity", y = "Confidence_Score", hue = "Compound", palette= "magma")
plt.title("Binding affinity of each compound")
sns.despine()
plt.plot()

# ==========================================
# SECTION 4: HIERARCHICAL INTERACTION MATRICES
# ==========================================

# 4.1 Reshaping for Hierarchical Clustering: Mean Affinity per Gene-Ligand Pair
df_pivot = df_docking.pivot_table(index = "Gene", columns = "Compound", values = "Binding_Affinity", aggfunc = "mean")
plt.figure(figsize=(10,8))
sns.clustermap(data = df_pivot, cmap = "magma")
plt.title("Binding affinity of each compound")
sns.despine()
plt.plot()

# The code to show Mean + Confidence Interval
# ==========================================
# SECTION 5: BIOASSAY CONFIDENCE INTERVALS
# ==========================================

# Simulating 100 observations for plant extract inhibition
np.random.seed(42)
data = {
    'Plant_Extract': np.random.choice(['Piper longum', 'Adhatoda vasica', 'Control'], 100),
    'Inhibition_Rate': np.random.normal(65, 12, 100),
    'Gene_Target': np.random.choice(['IL-6', 'TNF-alpha', 'COX-2'], 100)
}
df_bio = pd.DataFrame(data)
plt.figure(figsize=(10,6))
sns.pointplot(data=df_bio, x="Plant_Extract", y="Inhibition_Rate", capsize=.1)

plt.title("Mean Inhibition Rate with 95% Confidence Interval")
sns.despine()
plt.show()