# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gPGMk7sAn7p4JXvIn_5TuL6jYXuR_zDM
"""

"""
BIO-STATISTICAL VISUALIZATION SUITE - DAY 04
Focus: Distribution, Time-Series Metabolism, and Chemical Screening
Project: Tips Analysis and Virtual Compound Library
"""
import seaborn as sns
import matplotlib.pyplot as plt

# Load the standard tips dataset
tips = sns.load_dataset("tips")

# ==========================================
# SECTION 1: AGGREGATED CATEGORICAL TRENDS
# ==========================================

# 1.1 Cumulative Revenue Analysis
plt.figure(figsize =(10,8))
sns.barplot(data = tips, x = "day", y = "total_bill", estimator = "sum")
plt.title("Total Bill by Day")
sns.despine()
plt.show()

# 1.2 Correlation: Expenditure vs. Gratuity
plt.figure(figsize =(10,8))
sns.scatterplot(data = tips, x = "total_bill", y = "tip", hue = "smoker")
plt.title("Total Bill vs Tip")
sns.despine()
plt.show()

# ==========================================
# SECTION 2: PHARMACOKINETICS (TIME-SERIES)
# ==========================================
import pandas as pd
df_time = pd.DataFrame({
    'Hour': [1, 2, 3, 4, 5, 6],
    'Concentration': [0.5, 1.2, 2.8, 2.1, 1.5, 0.8]
})
plt.figure(figsize=(10,9))
sns.lineplot(data = df_time, x = "Hour", y = "Concentration", marker = "o")
plt.title("Drug Metabolism Over Time")
sns.despine()
plt.show()

# ==========================================
# SECTION 3: STATISTICAL DISTRIBUTIONS
# ==========================================

# 3.1 Frequency Distribution with Kernel Density Estimate
plt.figure(figsize=(10,9))
sns.histplot(data = tips, x = "total_bill", kde = True)
plt.title("Distribution of Total Bill")
sns.despine()
plt.show()

plt.figure(figsize=(10,9))
sns.boxplot(data = tips, x = "time", y = "tip")
plt.title("Tip Distribution by Meal Time")
sns.despine()
plt.show()

# ==========================================
# SECTION 4: VIRTUAL SCREENING & TOXICITY
# ==========================================

# 4.1 Synthetic Compound Library Generation (100 Compounds)
# 1. Create 100 random compounds
data = {
    'Binding_Affinity': [i for i in range(100)],
    'Molecular_Weight': [i**1.2 for i in range(100)],
    'Toxicity': ['Safe'] * 95 + ['TOXIC'] * 5  # Only 5 are dangerous
}
df_chem = pd.DataFrame(data)

# 2. Plotting with Hue
plt.figure(figsize=(10,6))
sns.scatterplot(data=df_chem,
                x='Binding_Affinity',
                y='Molecular_Weight',
                hue='Toxicity',
                palette={'Safe': 'lightgrey', 'TOXIC': 'red'}, # Red pops!
                s=100) # s=100 makes the dots a nice size

plt.title("Chemical Library: Highlighting Toxicity with Hue")
plt.show()