# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rf_z3jcb6EH4KOCUBGUoC6D2LC0g2gTC
"""

import seaborn as sns
import matplotlib.pyplot as plt
tips = sns.load_dataset("tips")
iris = sns.load_dataset("iris")

plt.figure(figsize =(10,8))
sns.barplot(data = tips, x = "day", y ="total_bill", order = ["Fri", "Sat", "Sun"])
plt.title("Average bill for each day")
sns.despine()
plt.show()

plt.figure(figsize =(10,8))
sns.lineplot(data = tips, x = "size", y = "total_bill", hue = "smoker", style = "smoker", marker = True)
plt.title("Total bill for size of table")
sns.despine()
plt.show()

plt.figure(figsize =(10,8))
sns.boxplot(data= tips, x = "total_bill", y = "day",hue = "sex", palette = "Set2")
plt.title("Dustribution of bill each day")
sns.despine()
plt.show()

plt.figure(figsize =(10,8))
sns.kdeplot(data = tips, x = "tip", hue = "time", fill = True, alpha = 0.4)
plt.title("density of tips for lunch and dinner")
sns.despine()
plt.show()

plt.figure(figsize =(10,8))
corr = iris.select_dtypes(include = "number").corr()
sns.heatmap(data = corr, annot = True, cmap = "coolwarm")
plt.title("physical measurement of flower")
sns.despine()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
compounds = pd.DataFrame({
    'Name': ['Compound A', 'Compound B'],
    'Value': [11, 12]
})
plt.figure(figsize =(10,8))
plt.ylim(10,13)
sns.barplot(data = compounds, x = "Name", y = "Value", palette="muted")
plt.title("Comparison of Compound Effectivesness")
sns.despine()
plt.show

