# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1heS3njwMeCUCrf7eIUcz7L37B0AfUXjq
"""

"""
ANTIOXIDANT KINETICS & PHENOLIC PROFILING - DAY 16
Focus: Extraction Method Efficiency, Phenolic-Antioxidant Correlation, and Log-Scale Normalization
Project: Piper longum vs. Adhatoda vasica Comparative Bioassay
"""
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

np.random.seed(30)
# ==========================================
# SECTION 1: ANTIOXIDANT ASSAY GENERATION
# ==========================================

# Research Data: Measuring free-radical scavenging activity across diverse solvents
data = {
    'Extract_Method': np.random.choice(['Methanolic', 'Aqueous', 'Ethanolic', 'Hexane'], 60),
    'Antioxidant_Activity': np.random.uniform(10, 95, 60), # % Inhibition
    'Phenolic_Content': np.random.uniform(5, 50, 60), # mg GAE/g
    'Plant_Species': np.random.choice(['Piper longum', 'Adhatoda vasica'], 60),
    'Trial_Duration': np.random.choice([12, 24, 48], 60) # Hours
}
df_antioxidant = pd.DataFrame(data)

# ==========================================
# SECTION 2: EXTRACTION METHODOLOGY AUDIT
# ==========================================

# 2.1 Experimental Sample Size per Solvent
plt.figure(figsize=(10,9))
sns.countplot(data = df_antioxidant, x = "Extract_Method", color = "skyblue")
plt.title("Trials conducted for each Extract Method")
sns.despine()
plt.show()

# 2.2 Global Correlation: Phenolic Concentration vs. Bioactivity
plt.figure(figsize=(10,8))
sns.scatterplot(data = df_antioxidant, x = "Phenolic_Content", y = "Antioxidant_Activity", color = "teal", s = 100)
plt.title("Phenolic Content vs. Antioxidant Activity")
sns.despine()
plt.show()

# ==========================================
# SECTION 3: DISTRIBUTION & SPECIES COMPARISON
# ==========================================

# 3.1 Comparative Bioactivity: Species-wise Distribution Density
# Violin plots show the kernel density estimation of the underlying data
plt.figure(figsize=(10,8))
sns.violinplot(data = df_antioxidant, x = "Plant_Species", y = "Antioxidant_Activity", palette = "muted")
plt.title("Antioxidant activity distribution by plant species")
sns.despine()
plt.show()

# 3.2 Bioactivity Histogram: Frequency and Kernel Density (KDE)
plt.figure(figsize=(10,8))
sns.histplot(data = df_antioxidant, x = "Antioxidant_Activity", kde = True, bins = 10, palette = "pastel")
plt.title("Distribution of Antioxidant Activity")
sns.despine()
plt.show()

# ==========================================
# SECTION 4: STRATIFIED MULTIVARIATE ANALYSIS
# ==========================================

# 4.1 Solvent Efficiency: Plotting Activity by Method Markers
plt.figure(figsize=(10,9))
sns.scatterplot(data = df_antioxidant, x = "Phenolic_Content", y = "Antioxidant_Activity", style = "Extract_Method", palette = "magma")
plt.title("Phenolic Content vs. Antifungal Activity")
sns.despine()
plt.show()

# ==========================================
# SECTION 5: LOG-SCALE TRANSFORMATION (TUESDAY WISDOM REVISITED)
# ==========================================

# Creating a log10 transformed column to handle wide-ranging biological responses
df_antioxidant['Log_Activity'] = np.log10(df_antioxidant['Antioxidant_Activity'])
# 5.1 Visualizing Wide-Range Data on Logarithmic Coordinates
plt.figure(figsize=(10,8))
sns.scatterplot(data = df_antioxidant, x = "Phenolic_Content", y = "Antioxidant_Activity")
plt.yscale('log')
plt.title("Antioxidant activity on a log10 scale")
plt.ylabel("Activity(Log10 % Inhibition)")
sns.despine()
plt.show()