# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18_oe7FRN8uynBwE0Uh5VCVB0udlTRRJJ
"""

"""
GENOMIC VISUALIZATION SUITE - THESIS PHASE 01
Focus: 22-Gene Docking Analysis & Pippali Phytochemical Screening
Project: Ethnopharmacology Research of Piper longum
"""
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Data for docking scores and molecular weight of 5 Pippali compounds
pippali_results = pd.DataFrame({
    'Compound': ['Comp_A', 'Comp_B', 'Comp_C', 'Comp_D', 'Comp_E'],
    'Docking_Score': [-9.2, -7.8, -8.5, -6.1, -9.8],
    'Molecular_Weight': [350, 410, 380, 290, 450],
    'Solubility': ['High', 'Low', 'Medium', 'High', 'Low']
})

# ==========================================
# SECTION 1: PIPPALI COMPOUND PRE-SCREENING
# ==========================================

# Data for docking scores and molecular weight of 5 Primary Pippali compounds
# 1.1 Compound Potency Ranking
plt.figure(figsize=(10,8))
sns.barplot(data = pippali_results, x = "Docking_Score", y = "Compound", palette="viridis")
plt.title("Docking Scores of Pippali Compounds")
sns.despine()
plt.show()

#Physicochemical Property Correlation
plt.figure(figsize=(10,8))
sns.scatterplot(data = pippali_results, x ="Molecular_Weight", y = "Docking_Score", hue = "Solubility")
plt.title("Relationship Between Molecular_Weight and Docking_Score")
sns.despine()
plt.show()

# ==========================================
# SECTION 2: DENSITY & FREQUENCY ANALYSIS
# ==========================================

# 2.1 Violin Plot: Density of Daily Tips
tips = sns.load_dataset("tips")
plt.figure(figsize=(10,8))
sns.violinplot(data = tips, x ="day", y ="total_bill")
plt.title("density of daily tips")
sns.despine()
plt.show()

# 2.2 Histogram: Distribution of Molecular Weight
# Using 4 bins as per your specific research logic
plt.figure(figsize=(10,9))
sns.histplot(data = pippali_results, x = "Molecular_Weight", bins = 4,kde = True)
plt.title("Distribution of Molecular Weight across compounds")
sns.despine()
plt.show()

# ==========================================
# SECTION 3: VARIANCE & CATEGORICAL COMPARISON
# ==========================================

# 3.1 Box Plot: Lunch vs. Dinner Comparisons
tips = sns.load_dataset("tips")
plt.figure(figsize=(10,8))
sns.boxplot(data = tips, x = "time", y = "total_bill", hue = "sex")
plt.title("Comparing total_bill across Lunch vs Dinner")
sns.despine()
plt.show()

# ==========================================
# SECTION 4: 22-GENE DOCKING STRENGTH (THESIS DATA)
# ==========================================

# Primary Research Data: Gene Stratification by Type and Expression

# Research Data: 22 Genes
# Type: Protein Coding vs Non-Coding
# Expression: Low, Medium, High
data = {
    'Gene': [f'Gene_{i}' for i in range(1, 23)],
    'Docking_Score': [-9.1, -6.2, -8.4, -7.5, -9.9, -5.4, -8.1, -7.7, -9.0, -6.8,
                      -8.3, -7.2, -9.5, -5.9, -8.8, -7.4, -9.2, -6.1, -8.0, -7.9, -9.7, -5.2],
    'Binding_Energy': [42, 55, 48, 50, 40, 60, 47, 49, 41, 53, 46, 51, 39, 58, 43, 50, 40, 57, 48, 49, 38, 62],
    'Gene_Type': ['Protein-Coding', 'Non-Coding'] * 11,
    'Expression': ['Low', 'Medium', 'High', 'Medium', 'Low', 'High', 'Medium', 'Low', 'High', 'Low', 'Medium'] * 2
}
df_thesis = pd.DataFrame(data)
plt.figure(figsize=(10,8))
sns.scatterplot(data = df_thesis, x = "Docking_Score", y = "Binding_Energy", hue = "Expression", style = "Gene_Type", s= 100)
plt.title("Docking Score vs Binding Energy")
sns.despine()
plt.show()

# --- 1. Horizontal Bar (Gene vs Score) ---
plt.figure(figsize=(10,8))
# Sorting by score makes it a 'Ranked' plot (Wisdom!)
sns.barplot(data=df_thesis.sort_values("Docking_Score"),
            x="Docking_Score", y="Gene", palette="magma")
plt.title("Ranking Genes by Docking Strength")
plt.show()

# --- 2. KDE Plot (Density of Binding Energy) ---
plt.figure(figsize=(10,6))
sns.kdeplot(data=df_thesis, x="Binding_Energy", fill=True, color="teal")
plt.title("Probability Density of Binding Energy")
plt.show()

# --- 3. Box Plot (Score by Expression) ---
plt.figure(figsize=(10,6))
sns.boxplot(data=df_thesis, x="Expression", y="Docking_Score", palette="Set2")
plt.title("Docking Score Distribution by Expression Level")
plt.show()

# --- 4. Scatter Plot (Simplified by Type) ---
plt.figure(figsize=(10,6))
sns.scatterplot(data=df_thesis, x="Docking_Score", y="Binding_Energy",
                hue="Gene_Type", s=100)
plt.title("Relationship colored by Gene Type")
plt.show()

# --- 5. Violin Plot (Energy Distribution by Type) ---
plt.figure(figsize=(10,6))
sns.violinplot(data=df_thesis, x="Gene_Type", y="Binding_Energy", inner="quart")
plt.title("Binding Energy Density by Gene Type")
plt.show()