# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z5RvPiJ8HBJas5wrVCp32dalYDq--bUk
"""

"""
BIOINFORMATICS & EXPLORATORY DATA ANALYSIS (EDA) - DAY 01
Focus: Statistical Distributions, Categorical Analysis, and Relationship Mapping
Author: Anushka Bhagra
Date: April 13, 2026
"""
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")

# ==========================================
# SECTION 1: Standard EDA (Tips Dataset)
# Goal: Practice distribution, comparison, and correlation plots.
# ==========================================
#  Distribution Analysis (Histogram + KDE
plt.figure(figsize=(10,8))
sns.histplot(data = tips , x = "tip", kde = True, color = "purple")
plt.title("Tips Distribution")
sns.despine()
plt.show()

#Categorical Comparison (Bar Plot)
plt.figure(figsize=(10,9))
sns.barplot(data = tips, x = "sex", y = "total_bill",hue = "day", palette = "Set1")
plt.title("Total Bill by Sex")
sns.despine()
plt.show()

# Outlier Detection (Box Plot)
sns.set_style("darkgrid")
plt.figure(figsize =(10,9))
sns.boxplot(data = tips, x = "day", y = "total_bill")
plt.title("Distribution of Bill Around the Week")
sns.despine()
plt.show()

plt.figure(figsize=(10,9))
sns.scatterplot(data = tips, x = "total_bill", y = "tip", hue = "smoker")
plt.title("Bill vs Tips")
sns.despine()
plt.show()

# Categorical Comparison (Bar Plot)
plt.figure(figsize=(10,9))
sns.barplot(data = tips, x = "day", y ="tip", hue ="size" , order=["Thur","Fri", "Sat","Sun"], palette ="viridis")
plt.title("Average Tips For Each Day")
sns.despine()

#  Multi-Dimensional Correlation (Scatter Plot)
plt.figure(figsize=(10,9))
sns.scatterplot(data = tips, x = "total_bill", y = "tip", hue ="size", palette="ch:s=-.2,r=.6")
plt.title("Bill vs Tips")
sns.despine()
plt.show()

# ==========================================
# SECTION 2: Bioinformatics Visualization
# Goal: Comparative analysis of Gene-Ligand Docking results.
# ==========================================
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data representing 10 different gene-ligand docking results
viz_data = {
    'Binding_Score': [-8.1, -7.2, -9.5, -8.8, -6.4, -7.9, -8.3, -7.1, -9.2, -8.5],
    'Function': ['Enzyme', 'Enzyme', 'Enzyme', 'Enzyme', 'Enzyme',
                 'Receptor', 'Receptor', 'Receptor', 'Receptor', 'Receptor']
}

df_viz = pd.DataFrame(viz_data)
plt.figure(figsize = (10,8))
sns.kdeplot(data = df_viz , x = "Binding_Score",hue = "Function", palette = "magma")
plt.title("Distribution of Binding Scores")
sns.despine()
plt.show()