# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QbzItCRSTo-PmE7nC-QaabPmCcMmaox_
"""

"""
BIOMETRIC & STATISTICAL VISUALIZATION - DAY 06
Focus: Distribution Variance, Correlation Heatmaps, and Comparative Assays
Project: Tips Analysis and Iris Morphological Measurements
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Load standard datasets for analysis
tips = sns.load_dataset("tips")
iris = sns.load_dataset("iris")

# ==========================================
# SECTION 1: CATEGORICAL & TREND ANALYSIS
# ==========================================

# 1.1 Mean Value Distribution by Day
plt.figure(figsize=(10, 8))
sns.barplot(data=tips, x="day", y="total_bill", order=["Fri", "Sat", "Sun"])
plt.title("Average Bill Expenditure per Scheduled Day")
sns.despine()
plt.show()

# 1.2 Multi-Variable Trend Analysis (Size vs. Bill)
plt.figure(figsize=(10, 8))
sns.lineplot(data=tips, x="size", y="total_bill", hue="smoker", style="smoker", marker=True)
plt.title("Linear Trend: Total Bill Correlation with Table Size")
sns.despine()
plt.show()

# ==========================================
# SECTION 2: DISTRIBUTION & DENSITY STUDIES
# ==========================================

# 2.1 Variance Analysis (Boxplot Distribution)
plt.figure(figsize=(10, 8))
sns.boxplot(data=tips, x="total_bill", y="day", hue="sex", palette="Set2")
plt.title("Statistical Distribution of Bills across Daily Categories")
sns.despine()
plt.show()

# 2.2 Kernel Density Estimation (Gratuity Study)
plt.figure(figsize=(10, 8))
sns.kdeplot(data=tips, x="tip", hue="time", fill=True, alpha=0.4)
plt.title("Probability Density: Tip Distribution for Lunch vs. Dinner")
sns.despine()
plt.show()

# ==========================================
# SECTION 3: BIOMETRIC CORRELATION (IRIS)
# ==========================================

# 3.1 Feature Correlation Heatmap
# Crucial for identifying co-dependent biological traits
plt.figure(figsize=(10, 8))
corr = iris.select_dtypes(include="number").corr()
sns.heatmap(data=corr, annot=True, cmap="coolwarm")
plt.title("Biometric Correlation: Iris Morphological Measurements")
sns.despine()
plt.show()

# ==========================================
# SECTION 4: COMPARATIVE PHARMACOLOGICAL ASSAY
# ==========================================

compounds = pd.DataFrame({
    'Name': ['Compound A', 'Compound B'],
    'Value': [11, 12]
})

plt.figure(figsize=(10, 8))
plt.ylim(10, 13)

# Professional Note: Added hue and legend settings for modern Seaborn compliance
sns.barplot(data=compounds, x="Name", y="Value", hue="Name", palette="muted", legend=False)

plt.title("Comparative Analysis: Compound Effectiveness Metrics")
sns.despine()

# Corrected: Added missing () to ensure the plot renders in local scripts
plt.show()