# -*- coding: utf-8 -*-
"""Untitled46.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oEq7iNC9O3icIvzj9sd9oO8lM4q44Ax3
"""

"""
ANTIBACTERIAL SYNERGY KINETICS & CHECKERBOARD MODELING - DAY 33
Focus: Combination Index (CI) Distributions, Fractional Drug Slopes, and Synergy Threshold Faceting
Project: Synergy Profiling of Piperaceae Alkaloids Combined with Conventional Antibiotics
"""
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

np.random.seed(88)
# ==========================================
# SECTION 1: ANTIBIOTIC CO-ASSAY GENERATION
# ==========================================
combinations = [
    'Piperine + Amoxicillin',
    'Piperlongumine + Ciprofloxacin',
    'Sylvatin + Tetracycline',
    'Crude_Extract + Amoxicillin'
]
bacteria = ['E. coli', 'S. aureus']

rows = []
for comb in combinations:
    for bug in bacteria:
        # 15 different concentration ratios per combination
        for ratio_idx in range(15):
            # Fraction of Phytochemical in the mix (0.0 to 1.0)
            fraction_phyto = np.linspace(0, 1, 15)[ratio_idx]

            # Generating a Combination Index (CI)
            # CI < 1 means Synergy (Good!), CI == 1 Additive, CI > 1 Antagonism
            if 'Piperine' in comb or 'Piperlongumine' in comb:
                base_ci = 1.2 - (fraction_phyto * 0.8) # Drops below 1.0 (Synergy)
            else:
                base_ci = 0.9 + (fraction_phyto * 0.4) # Goes above 1.0 (Antagonism)

            ci_value = max(0.2, base_ci + np.random.normal(0, 0.1))

            rows.append({
                'Combination': comb,
                'Bacterial_Strain': bug,
                'Fraction_Phytochemical': fraction_phyto,
                'Combination_Index': ci_value,
                'Zone_of_Inhibition_mm': max(0, 30 - (ci_value * 12) + np.random.normal(0, 1.5))
            })

df_synergy = pd.DataFrame(rows)
print("Dataset 'df_synergy' initialized successfully for your session!")

# ==========================================
# SECTION 2: EXPERIMENTAL MATRIX DENSITY
# ==========================================

# 2.1 Quantifying Replicate Saturation Across Bacterial Classes
plt.figure(figsize=(10,9))
sns.countplot(data = df_synergy, x = "Bacterial_Strain", hue = "Combination", color = "teal")
plt.title("counting data pointed for each bacterial strain")
sns.despine()

# 2.2 Global Interaction Spread: Frequency of Synergy Scores
plt.figure(figsize=(10,9))
sns.histplot(data = df_synergy, x = "Combination_Index", kde = True, palette = "magma")
plt.title("Overall Distribution shape of Histogram")
sns.despine()

# ==========================================
# SECTION 3: POTENCY VARIANCE & DRUG TIERS
# ==========================================

# 3.1 Comparative Spread: Boxplot tracking which combinations yield the lowest CI values
plt.figure(figsize=(10,9))
sns.boxplot(data = df_synergy, x = "Combination", y = "Combination_Index", color = "darkblue")
plt.title("Combination yields the lowest")
sns.despine()

# 3.2 Ratio-Dependent Shifts: Global Scatter Mapping
plt.figure(figsize=(10,9))
sns.scatterplot(data = df_synergy, x = "Fraction_Phytochemical", y = "Combination_Index", hue = "Combination", palette = "magma")
plt.title("Fraction vs Synergy")
sns.despine()

# ==========================================
# SECTION 4: FACETED SYNERGY FACES & THRESHOLDS
# ==========================================

# 4.1 Co-Faceted Line Plots: Separating Gram-Negative and Gram-Positive Responders
g = sns.relplot(
    data=df_synergy,
    x="Fraction_Phytochemical",
    y="Combination_Index",
    hue="Combination",       # Distinct color for each treatment mixture
    col="Bacterial_Strain",  # Splits into side-by-side columns (E. coli vs. S. aureus)
    kind="line",             # Connects the ratio steps with trend lines
    marker="o",              # Adds data point markers on each line
    palette="magma",
    height=5,
    aspect=1
)

# Customize the multi-plot figure layout
g.fig.suptitle("Q5: Synergy Profile Across Bacterial Strains", y=1.05)
g.set_axis_labels("Fraction of Phytochemical", "Combination Index (CI)")

# Add a horizontal reference line at CI = 1.0 to each subplot
for ax in g.axes.flat:
    ax.axhline(y=1.0, color='red', linestyle='--', alpha=0.7)

plt.show()