# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ppL6cxRYy-QCeapgNBbD1WXGSqSj1QUD
"""

"""
QUANTITATIVE RT-qPCR GENE PROFILING & RESCUE MODELING - DAY 34
Focus: Relative Expression Fold Changes, Jittered Stripplots, and Faceted Errorbar Categorization
Project: Evaluative Efficacy of Piperine on LPS-Induced Pro-Inflammatory Cascades
"""
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

np.random.seed(24)
# ==========================================
# SECTION 1: IN VITRO REPLICATE MAPPING
# ==========================================
genes = ['TNF-alpha', 'IL-6', 'IL-1beta', 'COX-2', 'iNOS']
treatments = ['Control', 'LPS_Induced', 'Piperine_Low', 'Piperine_High', 'Dexamethasone']
replicates = ['R1', 'R2', 'R3']

rows = []
for g in genes:
    for t in treatments:
        for r in replicates:
            # Baseline untreated control set around 1.0 fold change
            if t == 'Control':
                expr = np.random.normal(1.0, 0.15)
            # Lipopolysaccharide (LPS) induces a massive pro-inflammatory surge
            elif t == 'LPS_Induced':
                expr = np.random.normal(8.5, 1.2) if g in ['TNF-alpha', 'IL-6', 'IL-1beta'] else np.random.normal(5.0, 0.8)
            # Piperine low dose begins rescuing the cells
            elif t == 'Piperine_Low':
                expr = np.random.normal(5.5, 0.8) if g in ['TNF-alpha', 'IL-6', 'IL-1beta'] else np.random.normal(3.5, 0.5)
            # Piperine high dose significantly suppresses the expression
            elif t == 'Piperine_High':
                expr = np.random.normal(2.5, 0.4) if g in ['TNF-alpha', 'IL-6', 'IL-1beta'] else np.random.normal(1.8, 0.3)
            # Dexamethasone (Standard Positive Control Drug) knocks expression near baseline
            elif t == 'Dexamethasone':
                expr = np.random.normal(1.5, 0.2)

            rows.append({
                'Gene': g,
                'Treatment': t,
                'Replicate': r,
                'Relative_Expression': max(0.1, expr) # Fold change cannot be negative
            })

df_rna = pd.DataFrame(rows)
print("Dataset 'df_rna' initialized successfully for your Tuesday session!")

# ==========================================
# SECTION 2: EXPERIMENTAL SETUP VERIFICATION
# ==========================================

# 2.1 Audit of Assay Point Balance across Treatment Groups
plt.figure(figsize=(10,9))
sns.countplot(data = df_rna, x = "Treatment", hue = "Gene", color = "teal")
plt.title("Showing enteries for each treatment group")
sns.despine()
plt.show()

# 2.2 Global Variance Distribution: Histogram with KDE overlay
plt.figure(figsize=(10,9))
sns.histplot(data = df_rna, x = "Relative_Expression", kde = True, color = "indigo")
plt.title("Showing distribution of relative expression")
sns.despine()
plt.show()

# ==========================================
# SECTION 3: EXPRESSION SPREAD & DISPERSION
# ==========================================

# 3.1 Global Distribution Spread: Evaluating global treatment variances
plt.figure(figsize=(10,9))
sns.boxplot(data = df_rna, x = "Treatment", y = "Relative_Expression", palette = "magma")
plt.title("Showing boxplot of relative expression")
sns.despine()
plt.show()

# 3.2 Discrete Sample Scatter Matrix: Jittered Stripplot with Hue Partitioning
# Dodge=True separates your gene markers cleanly across the categorical axis
plt.figure(figsize=(10,9))
sns.stripplot(data = df_rna, x = "Treatment", y ="Relative_Expression", hue = "Gene", palette = "magma", dodge = True, jitter=0.2)
plt. title("Showing stripplot of relative expression")
sns.despine()
plt.show()

# ==========================================
# SECTION 4: MULTI-PANEL EXPRESSION PROFILES
# ==========================================

# 4.1 Faceted Facies Generation: Independent qPCR Bar charts with standard error bounds
g = sns.catplot(
    data=df_rna,
    x="Treatment",
    y="Relative_Expression",
    col="Gene",           # Splits each gene target into its own separate subplot panel
    kind="bar",          # Renders standard thesis bar graphs
    palette="magma",
    height=5,
    aspect=0.8,
    errorbar="se"        # Adds standard error bars to show structural data reliability
)

# Polishing the figure-level layout
g.fig.suptitle("Q5: RT-qPCR Expression Profiles across Inflammatory Targets", y=1.08, weight='bold')
g.set_axis_labels("", "Relative Expression (Fold Change)")
g.set_xticklabels(rotation=45) # Tilts your treatment words so they never overlap

plt.show()