# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UwMNQ3YuScdlmXzr9Xr1CgTQarnUyOi9
"""

"""
ENZYME KINETICS & PHYTOMEDICINAL REGRESSION - DAY 32
Focus: Alpha-Glucosidase & Alpha-Amylase Inhibition, Linear Regression Fitting, and Faceted Grids
Project: Comparative Efficacy of Piper longum Alkaloids vs. Crude Ethanol Extract
"""
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

np.random.seed(42)
# ==========================================
# SECTION 1: IN VITRO ENZYME INHIBITION ASSAY
# ==========================================
compounds = ['Piperine', 'Piperlongumine', 'Pellitorine', 'Guineensine', 'Crude_Ethanol']
enzymes = ['Alpha-Glucosidase', 'Alpha-Amylase']
concentrations = [10, 50, 100, 250, 500] # ppm

rows = []
for c in compounds:
    for e in enzymes:
        for conc in concentrations:
            for rep in ['R1', 'R2', 'R3']:
                # Scientific logic: Pure alkaloid piperine/piperlongumine inhibits more than crude at lower doses
                base_inhibition = (conc / 500) * 85 if c in ['Piperine', 'Piperlongumine'] else (conc / 500) * 60
                if e == 'Alpha-Glucosidase':
                    base_inhibition += 10 # slightly higher affinity for glucosidase

                inhibition = min(100, max(0, base_inhibition + np.random.normal(0, 4)))
                rows.append({
                    'Phytochemical': c,
                    'Enzyme_Target': e,
                    'Concentration_ppm': conc,
                    'Inhibition_Percent': inhibition,
                    'Replicate': rep
                })

df_enzyme = pd.DataFrame(rows)
print("Dataset 'df_enzyme' initialized successfully!")

# ==========================================
# SECTION 2: EXPERIMENTAL DESIGN DENSITY
# ==========================================

# 2.1 Quantifying Replicate Saturation Across Concentration Brackets
plt.figure(figsize=(10,9))
sns.countplot(data = df_enzyme, x = "Phytochemical", hue = "Concentration_ppm", color = "teal")
plt.title("Occurrences of each phytochemical in the dataset")
sns.despine()

# 2.2 Global Inhibition Profile: Frequency and Kernel Density Estimation (KDE)
plt.figure(figsize=(10,9))
sns.histplot(data = df_enzyme, x = "Inhibition_Percent", kde = True, color = "darkblue")
plt.title("Distribution of inhibition percentages")
sns.despine()

# ==========================================
# SECTION 3: PHARMACOLOGICAL POTENCY VARIANCE
# ==========================================

# 3.1 Comparative Spread: Boxplot evaluation of isolated compounds vs. crude mixtures
plt.figure(figsize=(10,8))
sns.boxplot(data = df_enzyme, x = "Phytochemical", y = "Inhibition_Percent", color = "darkblue")
plt.title("Boxplot of inhibition percentages by phytochemical")
sns.despine()

# 3.2 Dose-Response Trends: Global Lineplot Overlap
plt.figure(figsize=(10,9))
sns.lineplot(data = df_enzyme, x = "Concentration_ppm", y = "Inhibition_Percent", hue = "Phytochemical", palette = "dark")
plt.title("Concentration vs. Inhibition")
sns.despine()

#==========================================
# SECTION 4: CO-FACETED LINEAR REGRESSION
# ==========================================

# 4.1 Grid Faceting: Generating independent regression slopes for each enzyme target
# lmplot fits a linear model and plots the resulting regression line alongside its shaded 95% CI

g = sns.lmplot(
    data=df_enzyme,
    x="Concentration_ppm",
    y="Inhibition_Percent",
    col="Enzyme_Target",
    hue="Phytochemical",   # Optional: colors lines by your compounds
    palette="magma",
    height=5,
    aspect=1
)

g.fig.suptitle("Linear Regression: Concentration vs. Inhibition", y=1.05)
plt.show()