# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qyj2TxUY6YIpm73I4DiGUrxh7lBeaRyd
"""

"""
STATISTICAL DATA VISUALIZATION - DAY 02
Focus: Multi-plot Layouts, Regression Analysis, and Correlation Mapping
"""
import seaborn as sns
import matplotlib.pyplot as plt
# 1. Global Theming for Professional Clarity
# Load the built-in tips dataset
tips = sns.load_dataset("tips")

# Set a clean theme for all plots
sns.set_theme(style="whitegrid")

# ==========================================
# SECTION 1: CATEGORICAL & DENSITY ANALYSIS
# ==========================================
plt.figure(figsize=(10,8))
sns.barplot(data = tips, x = "day", y = "total_bill", hue = "time", order = ["Thur", "Fri", "Sat", "Sun"])
plt.title("Average total bill for each day")
sns.despine()
plt.show()

#Density Distribution (Smoker vs Non-Smoker)
plt.figure(figsize=(10,8))
sns.kdeplot(data = tips, x = "total_bill", hue = "smoker", fill = True, palette = "coolwarm")
plt.title("Distribution of total bill for smokers and non-smokers")
sns.despine()

plt.show()

# ==========================================
# SECTION 2: MULTI-PANEL BIOINFORMATICS LAYOUT
# ==========================================
plt.figure(figsize=(10,9))
plt.subplot(2,1,1)
sns.boxplot(data = tips, x = "tip", y = "day")
plt.subplot(2,1,2)
sns.scatterplot(data = tips, x = "total_bill", y ="tip")
plt.title("Boxplot of tip by day and scatterplot of total bill vs tip")
plt.tight_layout()
sns.despine()
plt.show()

# ==========================================
# SECTION 3: RELATIONSHIP & TREND MAPPING
# ==========================================
plt.figure(figsize=(10,9))
sns.regplot(data = tips, x = "total_bill", y = "tip", scatter_kws ={"color": "black"}, line_kws={"color": "red"})
plt.title("Relationship between Bill and Tip (with Trend Line)")
sns.despine()
plt.show()

#Numerical Correlation Matrix
# Essential for gene-gene interaction studies
plt.figure(figsize=(8,6))
corr_matrix = tips.select_dtypes('number').corr()
sns.heatmap(data = corr_matrix, annot = True, cmap = "YlGnBu")
plt.title("Correlation Heatmap of Numerical Features")
plt.show()

# You set up the figure
plt.figure(figsize=(10, 8))

# PLOT 1: The Boxplot
plt.subplot(2, 1, 1)
sns.boxplot(data=tips, x="day", y="total_bill")

# PLOT 2: The Scatterplot
plt.subplot(2, 1, 2)
sns.scatterplot(data=tips, x="total_bill", y="tip")
plt.title("Boxplot and Scatterplot of Total Bill vs Tip")
plt.tight_layout()
sns.despine()
plt.show()