# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NmPOjhwaE-lyvcfDToLRfoK5-1_KZrJo
"""

"""
GENOMIC VALIDATION & CELLULAR KINETICS - DAY 09
Focus: Gene Family Distribution, Correlation Heatmaps, and Growth Curve Dynamics
Project: 22-Gene Screening and Time-Series Growth Assay
"""
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Setting a seed so your results match mine!
np.random.seed(42)
# ==========================================
# SECTION 1: GENOMIC DATASET GENERATION
# ==========================================
# Generating the 22-gene dataset
data = {
    'Gene_ID': [f'Gene_{i}' for i in range(1, 23)],
    'Docking_Score': np.random.uniform(-11.0, -5.0, 22),
    'Binding_Energy': np.random.uniform(30, 70, 22),
    'Gene_Family': ['Kinase', 'Protease', 'Polymerase', 'Kinase', 'Protease'] * 4 + ['Kinase', 'Protease'],
    'Validation_Status': ['Verified', 'Predicted'] * 11
}

df_genes = pd.DataFrame(data)

# Sort it by score to make ranking easier later
df_genes = df_genes.sort_values('Docking_Score')

# ==========================================
# SECTION 2: COMPARATIVE AFFINITY ANALYSIS
# ==========================================

# 2.1 Ranked Docking Profile
plt.figure(figsize=(10,6))
sns.barplot(data = df_genes, x = "Gene_ID", y = "Docking_Score", color = "blue")
plt.title("Docking score for all genes")
sns.despine()
plt.xticks(rotation = 45)
plt.show()

# 2.2 Numerical Property Correlation
df_corr = df_genes.corr(numeric_only=True )
plt.figure(figsize=(10,8))
sns.heatmap(data = df_corr, annot = True, cmap = "coolwarm")
plt.title("Correlation matrix")
plt.show()

# ==========================================
# SECTION 3: DISTRIBUTION & DENSITY STUDIES
# ==========================================

# 3.1 Functional Distribution (Docking Score by Gene Family)
plt.figure(figsize=(10,8))
sns.histplot(data = df_genes, x = "Docking_Score", hue = "Gene_Family", kde = True, color = "blue")
plt.title("Docking score for all genes")
sns.despine()
plt.show()

# 3.2 Binding Energy Density Ma
plt.figure(figsize=(10,8))
sns.histplot(data = df_genes, x = "Binding_Energy", kde = True, color = "purple")
plt.title("Binding energy Density")
sns.despine()
plt.show()

# 3.3 Status-Driven Correlation: Score vs. Energy
plt.figure(figsize=(10,8))
sns.scatterplot(data = df_genes, x = "Docking_Score", y = "Binding_Energy", hue = "Validation_Status", color = "magma")
plt.title("Relationship between Docking score and Binding energy")
sns.despine()
plt.show()

# ==========================================
# SECTION 4: KINETIC RESEARCH (CELL GROWTH)
# ==========================================
# Experimental Data: Time vs. Cell Growth
research_data = {
    'Hour': [0, 2, 4, 6, 12, 24],
    'Cell_Count': [100, 150, 210, 280, 50, 10]
}
df_study = pd.DataFrame(research_data)
plt.figure(figsize=(10,8))
sns.scatterplot(data = df_study, x = "Hour", y = "Cell_Count", color = "red")
plt.title("Time vs. Cell Growth")
sns.despine()
plt.show()