# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YrU-hG1o9RJljkHYN-R41KGozfeaWLA5
"""

"""
Bioinformatics Analysis Suite: Gene Expression Visualization
Script for Piper longum Thesis - Practice Session
"""
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

np.random.seed(27) # For 27th April!

data = {
    'Gene_Symbol': [f'GENE_{i:02d}' for i in range(1, 21)],
    'Tissue_Type': np.random.choice(['Liver', 'Heart', 'Lung', 'Brain'], 20),
    'Expression_Level': np.random.lognormal(mean=2, sigma=0.8, size=20),
    'Fold_Change': np.random.uniform(-3, 3, 20),
    'P_Value': np.random.uniform(0, 0.05, 20),
    'Protein_Concentration': np.random.uniform(10, 500, 20)
}
df_genes = pd.DataFrame(data)

# --- 2. Tissue Census (Countplot) ---
    # Purpose: Visualizing the distribution of target genes across tissue types
plt.figure(figsize=(10,8))
sns.countplot(data = df_genes, x = "Tissue_Type", hue= "Tissue_Type", palette = "Set2")
plt.title("Number of genes expressed per tissue types")
sns.despine()
plt.show()

# --- 3. Gene Expression Ranking (Sorted Barplot) ---
    # Note: Professional plots are sorted to immediately identify top candidates
plt.figure(figsize=(10,8))
sns.barplot(data = df_genes, x = "Expression_Level", y = "Gene_Symbol")
plt.title("Gene expression level")
sns.despine()
plt.show()

# --- 4. Statistical Significance Distribution (Histplot) ---
    # Purpose: Verifying the p-value enrichment to ensure experimental health
plt.figure(figsize=(10,8))
sns.histplot(data = df_genes, x = "P_Value", bins = 10, kde = True)
plt.title("P-value distribution")
sns.despine()
plt.show()

# --- 5. mRNA vs. Protein Correlation (Scatterplot) ---
    # Purpose: Investigating translation efficiency across tissues
plt.figure(figsize=(10,8))
sns.scatterplot(data = df_genes, x = "Expression_Level", y = "Protein_Concentration", hue = "Tissue_Type", palette = "Set2")
plt.title("Expression vs protein concentration")
sns.despine()
plt.show()

# --- 6. Tissue-Specific Regulation (Fold Change Barplot) ---
plt.figure(figsize=(10,8))
sns.barplot(data = df_genes, x = "Tissue_Type", y = "Fold_Change")
plt.title("Average change in the different tissue types")
sns.despine()
plt.show()

# Data: Both genes doubled (100% increase), but at different scales
# --- 7. The Wisdom Plot (Log-Scale Integrity) ---
    # Purpose: Proving that small regulators are as important as high-abundance proteins
wisdom_data = {
    'Gene_Name': ['Master_Regulator', 'Master_Regulator', 'Structural_Protein', 'Structural_Protein'],
    'Condition': ['Control', 'Treated', 'Control', 'Treated'],
    'Expression': [5, 10, 5000, 10000]
}

df_wisdom = pd.DataFrame(wisdom_data)
plt.figure(figsize=(10,8))
sns.barplot(data = df_wisdom, x = "Gene_Name", y = "Expression", hue = "Condition", palette = "muted")
plt.title("Gene expression level")
sns.despine()
plt.yscale('log')
plt.show()

