# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UzezyZxwVVnvh8CWoqTNuTYQqs38RgBG
"""

"""
MOLECULAR DOCKING & TRANSCRIPTOMIC CLUSTERING - DAY 15
Focus: Binding Affinity (kcal/mol), Bioavailability Correlation, and Hierarchical Gene Clustering
Project: Piper longum (Pippali) & Adhatoda vasica Polyherbal Response
"""
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

np.random.seed(29)
# ==========================================
# SECTION 1: MOLECULAR DOCKING DATASET
# ==========================================

# Simulating a docking assay: Lower Binding Affinity (negative kcal/mol) indicates higher potency
data = {
    'Phytochemical': np.random.choice(['Piperine', 'Vasicine', 'Pippali', 'Quercetin', 'Luteolin'], 50),
    'Binding_Affinity': np.random.uniform(-9.5, -4.0, 50), # kcal/mol (lower is better)
    'Molecular_Weight': np.random.uniform(200, 500, 50),
    'Plant_Part': np.random.choice(['Leaf', 'Fruit', 'Stem', 'Root'], 50),
    'Bioavailability_Score': np.random.uniform(0.1, 0.9, 50)
}
df_docking = pd.DataFrame(data)

# ==========================================
# SECTION 2: PHYTOCHEMICAL DISTRIBUTION
# ==========================================

# 2.1 Botanical Distribution of Leads
plt.figure(figsize=(10,9))
sns.countplot(data = df_docking, x = "Plant_Part", hue ="Phytochemical",  palette = "dark:blue")
plt.title("distribution of phytochemicals from differnent plants")
sns.despine()
plt.show()

# 2.2 Comparative Potency: Binding Affinity by Chemical Species
plt.figure(figsize=(10,9))
sns.barplot(data = df_docking, x = "Phytochemical", y = "Binding_Affinity", hue = "Plant_Part", palette = "magma")
plt.title("Binding affinity of phytochemicals")
sns.despine()
plt.show()

# ==========================================
# SECTION 3: PHARMACOKINETIC CORRELATIONS
# ==========================================

# 3.1 Potency vs. Bioavailability (First Pass)
plt.figure(figsize=(10,9))
sns.scatterplot(data = df_docking, x = "Binding_Affinity", y = "Bioavailability_Score", hue = "Plant_Part", palette = "viridis")
plt.title("Binding affinity of phytochemicals")
sns.despine()
plt.show()

# 3.2 Physical Property Spread: Molecular Weight
plt.figure(figsize=(10,9))
sns.histplot(data = df_docking, x = "Molecular_Weight", hue ="Phytochemical",  palette = "magma")
plt.title("distribution of molecular weight of phytochemicals")
sns.despine()
plt.show()

# 3.3 Potency vs. Bioavailability (Replication check
plt.figure(figsize=(10,9))
sns.scatterplot(data = df_docking, x = "Binding_Affinity", y = "Bioavailability_Score", hue = "Plant_Part", palette = "viridis")
plt.title("Binding affinity of phytochemicals")
sns.despine()
plt.show()

# ==========================================
# SECTION 4: TRANSCRIPTOMIC RESPONSE (HEATMAPS)
# ==========================================

# Generating 10 genes across 4 distinct herbal extract treatments
np.random.seed(30)
genes = [f'Gene_{chr(65+i)}' for i in range(10)]
treatments = ['Control', 'Piper_Longum_Ext', 'Adhatoda_Ext', 'Polyherbal_Formula']

# Create a matrix of expression values
data_heatmap = np.random.randn(10, 4)
df_heatmap = pd.DataFrame(data_heatmap, index=genes, columns=treatments)
# 4.1 Global Expression Profile
plt.figure(figsize=(10,8))
sns.heatmap(data = df_heatmap, annot = True , cmap = "RdBu_r")
plt.title("heatmap of expression of genes")
sns.despine()
plt.show()

# ==========================================
# SECTION 5: HIERARCHICAL CLUSTERING
# ==========================================

# Using a diverging palette: Red for Up-regulation, Blue for Down-regulation
# 'center=0' is crucial so that white represents no change
plt.figure(figsize=(10, 8))
g = sns.clustermap(df_heatmap,
                   cmap="RdBu_r",
                   center=0,
                   annot=True,
                   linewidths=.5,
                   cbar_kws={'label': 'Log2 Fold Change'})

g.fig.suptitle('Gene Expression Profile: Multi-Extract Response', y=1.02)
plt.show()