# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V4qbFB1MFma5urNW8JRU3aLNIhiP1zdg
"""

"""
ALKALOID PURITY & Z-SCORE NORMALIZATION - DAY 14
Focus: Inhibition Kinetics, Sample Distribution, and Individual Gene Normalization
Project: Piper longum (Pippali) Phytochemical Screening and Expression Analysis
"""
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# Reproducibility Seed for Academic Integrity
np.random.seed(28)
# ==========================================
# SECTION 1: PHYTOCHEMICAL ASSAY GENERATION
# ==========================================

# Research Data: Alkaloid Profiling across multiple Pippali sources
data = {
    'Alkaloid_Type': np.random.choice(['Piperine', 'Piperlongumine', 'Sylvatin', 'Pippali'], 40),
    'Purity_Percentage': np.random.uniform(85, 99.9, 40),
    'Inhibition_Rate': np.random.uniform(20, 95, 40),
    'Sample_Source': np.random.choice(['Root', 'Fruit', 'Stem'], 40),
    'Extraction_Temp': np.random.choice([30, 45, 60], 40)
}
df_assay = pd.DataFrame(data)

# ==========================================
# SECTION 2: SAMPLE & PURITY DISTRIBUTION
# ==========================================

# 2.1 Sample Source Frequency
plt.figure(figsize=(10,9))
sns.countplot(data = df_assay, x = "Sample_Source", hue = "Sample_Source", palette = "viridis")
plt.title("Sample Distribution by source")
sns.despine()
plt.show()

# 2.2 Purity-Inhibition Global Correlation
plt.figure(figsize=(10, 8))
sns.scatterplot(data=df_assay, x="Purity_Percentage", y="Inhibition_Rate", color="teal", s=100)
plt.title("Inhibition Rate vs. Purity Percentage")
sns.despine()
plt.show()

# 2.3 Purity Frequency Distribution (Density Map)
plt.figure(figsize=(10,8))
sns.histplot(data = df_assay, x = "Purity_Percentage", kde = True, color = "teal")
plt.title("Distribution of Purity Percentage")
sns.despine()
plt.show()

# ==========================================
# SECTION 3: ALKALOID TYPE ANALYSIS
# ==========================================

# 3.1 Mean Inhibition by Alkaloid Species
plt.figure(figsize=(10,8))
sns.barplot(data = df_assay, x =  "Alkaloid_Type", y = "Inhibition_Rate", color = "blue")
plt.title("Inhibition Rate vs. Purity Percentage")
sns.despine()
plt.show()

# 3.2 Stratified Potency: Purity vs. Inhibition by Type
plt.figure(figsize=(10,9))
sns.scatterplot(data = df_assay, x = "Purity_Percentage", y = "Inhibition_Rate", hue = "Alkaloid_Type", palette = "viridis")
plt.title("Inhibition Rate vs. Purity Percentage")
sns.despine()
plt.show()

# ==========================================
# SECTION 4: TUESDAY WISDOM (Z-SCORE NORMALIZATION)
# ==========================================

# Comparative Gene Expression Data (High vs. Low Abundance)
data_wisdom_2 = {
    'Gene_Name': ['Gene_X', 'Gene_X', 'Gene_Y', 'Gene_Y'],
    'Group': ['Control', 'Treated', 'Control', 'Treated'],
    'Raw_Expression': [1000, 2000, 10, 20]
}

df_standard = pd.DataFrame(data_wisdom_2)
#4.1 Intra-Gene Normalization via Lambda Transformation
# Applying Z-Score: (x - mean) / std to standardize
df_standard['Z_Score'] = df_standard.groupby('Gene_Name')['Raw_Expression'].transform(
    lambda x: (x - x.mean()) / x.std()
)

# 4.2 Visualization of Normalized Expression
plt.figure(figsize=(10, 8))
sns.barplot(data=df_standard, x='Gene_Name', y='Z_Score', hue='Group', palette='coolwarm')

plt.title("Z-Score Normalized Expression (Tuesday Wisdom)")
plt.ylabel("Z-Score (Standard Deviations from Mean)")
sns.despine()
plt.show()