# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gj8KHiG_V1cuw_JrvBWRjdaanDK4U7Qf
"""

"""
CYTOTOXICITY PROFILING & DOSE-RESPONSE MODELING - DAY 31
Focus: Selective Toxicity (Cancer vs. Healthy), Dose-Dependent Viability, and Grid-Faceting
Project: Comparative Evaluation of Plant Fractions across MCF-7, HeLa, and HEK-293 Lines
"""
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

np.random.seed(15)
# ==========================================
# SECTION 1: SYNTHETIC CYTOTOXICITY DATASET
# ==========================================
fractions = ['Aqueous', 'Methanolic', 'Ethanolic', 'Hexane']
cells = ['MCF-7', 'HeLa', 'HEK-293'] # Two cancer lines, one healthy control
concentrations = [0, 10, 50, 100, 250, 500]

# Generating synthetic data
rows = []
for f in fractions:
    for c in cells:
        for conc in concentrations:
            # Logic: Cancer cells (MCF-7, HeLa) die more than HEK-293
            base_death = (conc / 500) * 80 if c != 'HEK-293' else (conc / 500) * 20
            viability = max(0, 100 - base_death + np.random.normal(0, 5))
            rows.append({
                'Fraction': f,
                'Cell_Line': c,
                'Concentration_ug_ml': conc,
                'Cell_Viability': viability,
                'Apoptosis_Index': (100 - viability) / 10 + np.random.uniform(0, 2)
            })

df_cytotox = pd.DataFrame(rows)
print("Dataset 'df_cytotox' ready for practice!")

# ==========================================
# SECTION 2: EXPERIMENTAL SAMPLE DISTRIBUTION
# ==========================================

# 2.1 Audit of Assay Replicates per Fraction/Cell Line
plt.figure(figsize=(10,9))
sns.countplot(data = df_cytotox, x = 'Fraction', hue = 'Cell_Line')
plt.title("samples for each cell line")
sns.despine()
plt.show()

# ==========================================
# SECTION 3: DOSE-VIABILITY CORRELATIONS
# ==========================================

# 3.1 Global Scatter Profile: Viability as a Function of Concentration
plt.figure(figsize=(10,9))
sns.scatterplot(data = df_cytotox, x = "Concentration_ug_ml", y = "Cell_Viability", hue = "Cell_Line")
plt.title("Cell Viability vs Concentration")
sns.despine()

# 3.2 Viability Distribution Density: Histogram with KDE
plt.figure(figsize=(10,9))
sns.histplot(data = df_cytotox, x = "Cell_Viability", kde = True, hue = "Cell_Line", palette = "magma")
plt.title("Distribution of Cell Viability")
sns.despine()

# ==========================================
# SECTION 4: VARIANCE & SELECTIVE TOXICITY
# ==========================================

# 4.1 Categorical Variance: Boxplot analysis of Fraction Potency
plt.figure(figsize=(10,9))
sns.boxplot(data = df_cytotox, x = "Fraction", y = "Cell_Viability", hue = "Cell_Line")
plt.title("Cell viability by Fraction and Cell Line")
sns.despine()

# ==========================================
# SECTION 5: MULTI-FACETED DOSE-RESPONSE CURVES
# ==========================================

# 5.1 Grid Visualization: Line-plots for Dose-Response Comparison
# Creating a relational plot grid to isolate curves for each cell line
g = sns.relplot(
    data=df_cytotox,
    x="Concentration_ug_ml",
    y="Cell_Viability",
    hue="Fraction",
    col="Cell_Line",     # This is the parameter that creates the grid columns
    kind="line",         # Connects the doses to show a curve
    marker="o",
    height=5,
    aspect=0.8
)

# Adding a title to the whole figure
g.fig.title("Dose-Response Comparison across Cell Lines", y=1.05)

plt.show()