# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJK_JAvjAmICnHYwgG3cy6JQgNXb7qv2
"""

"""
WESTERN BLOT DENSITOMETRY PROFILING & PROTEIN EXPRESSION - DAY 35
Focus: Housekeeping Control Stability, Band Intensity Distributions, and Swarm Faceting
Project: Dose-Dependent Knockdown Efficacy of Extracts vs. Aspirin Positive Control
"""
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

np.random.seed(55)
# ==========================================
# SECTION 1: PROTEIN DENSITOMETRY GENERATION
# ==========================================
proteins = ['NF-kB (p65)', 'iNOS Protein', 'COX-2 Protein', 'Beta-Actin (Control)']
treatments = ['Control', 'LPS_Induced', 'Extract_25_ug', 'Extract_100_ug', 'Aspirin_Positive']
replicates = ['Bio_Rep1', 'Bio_Rep2', 'Bio_Rep3']

rows = []
for p in proteins:
    for t in treatments:
        for r in replicates:
            # Beta-Actin is the housekeeping loading control; it must remain stable across all lanes
            if p == 'Beta-Actin (Control)':
                intensity = np.random.normal(1.0, 0.05)
            else:
                if t == 'Control':
                    intensity = np.random.normal(0.2, 0.04) # Low baseline protein
                elif t == 'LPS_Induced':
                    intensity = np.random.normal(1.8, 0.15) # Intense protein expression band
                elif t == 'Extract_25_ug':
                    intensity = np.random.normal(1.3, 0.12) # Slight suppression
                elif t == 'Extract_100_ug':
                    intensity = np.random.normal(0.6, 0.08) # Strong dose-dependent suppression
                elif t == 'Aspirin_Positive':
                    intensity = np.random.normal(0.4, 0.05) # Positive drug control knockdown

            rows.append({
                'Protein_Target': p,
                'Treatment_Group': t,
                'Replicate_ID': r,
                'Relative_Band_Intensity': max(0.01, intensity)
            })

df_protein = pd.DataFrame(rows)
print("Dataset 'df_protein' initialized successfully for your Wednesday session!")

# 1. Separate your figure setup
plt.figure(figsize=(10, 6))

# 2. Filter the data using Pandas brackets inside the data argument
sns.barplot(
    data=df_protein[df_protein["Protein_Target"] == "Beta-Actin (Control)"],
    x="Treatment_Group",
    y="Relative_Band_Intensity",
    palette="mako"
)

# 3. Add labels and clean up axes
plt.title("Beta-Actin (Loading Control) Stability Profile")
plt.ylabel("Relative Band Intensity")
plt.xlabel("Treatment Group")
plt.xticks(rotation=15) # Tilts your labels so they don't overlap

sns.despine()
plt.show() # Added parentheses to execute the plot display

# ==========================================
# SECTION 3: POPULATION DENSITY & DISPERSION
# ==========================================

# 3.1 Global Intensity Spread: Distribution Curve and Histogram
plt.figure(figsize=(10,9))
sns.histplot(data = df_protein, x = "Relative_Band_Intensity", kde = True, palette = "magma")
plt.title("Distribution of Relative Band Intensities")
plt.xlabel("Relative Band Intensity")
plt.ylabel("Frequency")
sns.despine()
plt.show()

# 3.2 Interquartile Range Auditing: Boxplot Grouping
plt.figure(figsize=(10,9))
sns.boxplot(data = df_protein, x = "Treatment_Group", y = "Relative_Band_Intensity", hue = "Protein_Target", palette = "magma")
plt.title("Boxplot of Relative Band Intensities by Treatment Group")
plt.xlabel("Treatment Group")
plt.ylabel("Relative Band Intensity")
sns.despine()
plt.show()

# 3.3 Probability Density Profiles: Violin Plots
plt.figure(figsize=(10,9))
sns.violinplot(data = df_protein, x = "Treatment_Group", y = "Relative_Band_Intensity", hue = "Protein_Target", palette = "mako")
plt.title("Violin Plot of Relative Band Intensities by Treatment Group")
plt.xlabel("Treatment Group")
plt.ylabel("Relative Band Intensity")
sns.despine()
plt.show()

# ==========================================
# SECTION 4: FACETED REPLICATE DISTRIBUTIONS
# ==========================================

# 4.1 Categorical Swarm Grid: Displaying exact individual replicate point clouds
g = sns.catplot(data = df_protein, x = "Treatment_Group", y = "Relative_Band_Intensity", hue = "Protein_Target", kind = "swarm", col = "Protein_Target", palette = "magma", size = 6)
g.fig.suptitle("Swarm Plot of Relative Band Intensities by Treatment Group")
sns.despine()
plt.show()