# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ecNQcMJQkoxvW3P-v1J4EX6vKtVeZq1
"""

"""
PHARMACOKINETIC (PK) PROFILE ANALYSIS - DAY 11
Focus: Serum Concentration Kinetics, Metabolic Variance, and Multi-Panel Dashboards
Project: Longitudinal Drug Absorption Study across Multiple Subjects
"""
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

np.random.seed(42)
# ==========================================
# SECTION 1: RESEARCH DATASET GENERATION
# ==========================================

# Simulating a 24-hour PK study for 5 distinct subjects
data = {
    'Time_Point': [0, 1, 2, 4, 8, 12, 24] * 5,
    'Subject_ID': np.repeat(['Sub_A', 'Sub_B', 'Sub_C', 'Sub_D', 'Sub_E'], 7),
    'Serum_Concentration': np.random.uniform(0, 100, 35),
    'Metabolic_Rate': np.random.uniform(1.2, 5.5, 35),
    'Absorption_Category': np.random.choice(['Fast', 'Moderate', 'Slow'], 35),
    'Dosage_mg': np.random.choice([50, 100, 150], 35)
}
df_pk = pd.DataFrame(data)

# ==========================================
# SECTION 2: LONGITUDINAL KINETICS
# ==========================================

# 2.1 Individual Subject Clearance Curves
plt.figure(figsize=(10,8))
sns.lineplot(data = df_pk , x = "Time_Point", y = "Serum_Concentration", hue = "Subject_ID", marker = "o")
plt.title("Serum Concentration vs Time Point")
plt.grid(True, linestyle = '--', alpha=0.6)
sns.despine()
plt.show()

# ==========================================
# SECTION 3: METABOLIC & DOSAGE ANALYSIS
# ==========================================

# 3.1 Comparative Metabolic Rates by Dosage and Category
plt.figure(figsize=(10,8))
sns.barplot(data = df_pk , x = "Dosage_mg", y = "Metabolic_Rate", hue = "Absorption_Category", palette = "muted")
plt.title("Average metaboluc rate by dosage group")
sns.despine()
plt.show()

# 3.2 Distribution of Metabolic Observations
plt.figure(figsize=(10,8))
sns.histplot(data = df_pk, x = "Metabolic_Rate", bins = 10, kde = True, color = "skyblue")
plt.title("Distribution of Metabolic Rate")
sns.despine()
plt.show()

# 3.3 Correlation: Concentration vs. Metabolism
plt.figure(figsize=(10,9))
sns.scatterplot(data = df_pk, x = "Serum_Concentration", y = "Metabolic_Rate")
plt.title("Serum Concentration vs Metabolic Rate")
sns.despine()
plt.show()

plt.figure(figsize=(10,8))
sns.scatterplot(data = df_pk, x = "Time_Point", y = "Serum_Concentration", hue = "Absorption_Category", color = "green")
plt.title("Serum Concentration vs Time Point")
sns.despine()
plt.show()

# ==========================================
# SECTION 4: RESEARCH DASHBOARD (2X2 GRID)
# ==========================================

# Creating a high-impact summary figure for research publication
fig, axes = plt.subplots(2, 2, figsize=(15, 12))

# Plot 1: Top-Left (Line Plot of Trend)
sns.lineplot(data=df_pk, x="Time_Point", y="Serum_Concentration", ax=axes[0, 0])
axes[0, 0].set_title("Trend Over Time")

# Plot 2: Top-Right (Bar Plot of Dosage)
sns.barplot(data = df_pk, x = "Dosage_mg", y = "Metabolic_Rate", ax=axes[0,1])
axes[0, 1].set_title("Dosage vs Metabolic Rate")

# Plot 3: Bottom-Left (Histplot of Metabolism)
sns.histplot(data = df_pk, x = "Metabolic_Rate", bins = 10, kde = True, color = "skyblue", ax=axes[1, 0])
axes[1, 0].set_title("Distribution of Metabolic Rate")
# Plot 4: Bottom-Right (Scatter of Concentration vs Rate)
sns.scatterplot(data = df_pk , x = "Serum_Concentration", y = "Metabolic_Rate", ax = axes[1,1])
axes[1,1]. set_title("Serum Concentration vs Metabolic Rate")

# Adjust spacing between subplots
plt.tight_layout()
plt.show()