# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_kBgEN5gWLiYWnGLhCKfE46c-v0uMgWn
"""

import seaborn as sns
import matplotlib.pyplot as plt

scores = [55, 62, 65, 70, 71, 72, 75, 78, 80, 82, 85, 88, 90, 92, 95, 98]
#creating a histogram for getting frequency of test score of students

plt.figure(figsize=(10,7))
plt.title("Frequency of Test Scores")

sns.histplot(scores, bins=5, color = "skyblue", edgecolor = "black")
plt.xlabel('Exam Score')
plt.ylabel('Number of students')
plt.show()
# YOUR TASK:
# 1. Create a histplot.
# 2. Use bins=5 (this groups the scores into 5 big bars).
# 3. Add a title "Frequency of Test Scores".

import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")

# 1. Filter the data
plt.figure(figsize=(10,6))
filtered_tips = tips[tips['size'].isin([2, 4])]
sns.kdeplot(data = filtered_tips, x = "total_bill", hue = 'size', fill=True, palette = 'viridis')
plt.title("Bill Density: Tables of 2 vs. Tables of 4")
plt.show()
# 2. YOUR TURN: Write the KDE plot code below
# Hint: Use x="total_bill",

import seaborn as sns
import matplotlib.pyplot as plt

scores = [55, 62, 65, 70, 71, 72, 75, 78, 80, 82, 85, 88, 90, 92, 95, 98]
# creating a kde plot for making the smooth curvse and see what changes took place and what will be different in both
plt.figure(figsize=(8,4))
plt.title("Frequency of Test Score")
#using 10 bins for more detail and adding a KDE line
sns.histplot(scores, bins = 10, kde = True, color = "forestgreen", edgecolor = "blue")
plt.xlabel("Exam Score")
plt.ylabel("Number of students")
plt.show()
# YOUR TASK:
# 1. Create a histplot, but add the parameter kde=True.
# 2. Change the color to "forestgreen".
# 3. See how the line follows the tops of the bars!

import seaborn as sns
import matplotlib.pyplot as plt
#creating histogram to see if people tends to pay more tips during lunch or dinner
tips = sns.load_dataset("tips")
plt.figure(figsize=(10,8))
plt.title("Distribution of Bll Amounts: Lunch vs Dinner")
sns.histplot(data = tips, x='total_bill', hue ='time', element='step', kde = True)
plt.xlabel("Total Bill")
plt.ylabel("Number of people")
plt.show()
# YOUR TASK:
# 1. Create a histplot using data=tips.
# 2. Set x="total_bill".
# 3. Use hue="time" to see Lunch and Dinner overlapping.
# 4. Use element="step" to make the overlapping bars easier to see!