# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iavH8OJbkr4O181DgvdNhguSj5T7lst7
"""

"""
PHYTOCHEMICAL CHARACTERIZATION SUITE - DAY 08
Focus: Concentration Dynamics, Bioactivity Correlation, and Multi-Panel Assays
Project: Piper longum (Pippali) Ethnopharmacological Research
"""
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Research Data: Phytochemicals in Piper longum (Pippali)
pippali_data = pd.DataFrame({
    'Phytochemical': ['Piperine', 'Piperlongumine', 'Sylvatin', 'Guineensine', 'Piperonal'],
    'Concentration_mg_g': [45.2, 12.8, 5.4, 8.9, 2.1],
    'Solubility_Index': [0.85, 0.40, 0.15, 0.30, 0.05],
    'Bioactivity_Score': [9.2, 8.4, 4.1, 6.7, 3.2]
})

# ==========================================
# SECTION 1: PRIMARY DISTRIBUTION & AFFINITY
# ==========================================

# 1.1 Concentration Profile by Phytochemical
plt.figure(figsize=(10,8))
sns.barplot(data = pippali_data, x = "Concentration_mg_g", y = "Phytochemical", hue = "Solubility_Index", palette = "magma")
plt.title("Phytochemical vs Concentration")
sns.despine()
plt.show()

# 1.2 Multi-Variant Analysis: Concentration vs. Bioactivity
# Size denotes Solubility Index for 3D data representation
plt.figure(figsize=(10,8))
sns.scatterplot(data = pippali_data, x ="Concentration_mg_g", y = "Bioactivity_Score", size = "Solubility_Index")
plt.title("Concentration vs Bioactivity Score")
sns.despine()
plt.show()

# ==========================================
# SECTION 2: STATISTICAL RELATIONSHIPS
# ==========================================

# 2.1 Joint Regression Analysis
# Examining the linear relationship between quantity and therapeutic potential
plt.figure(figsize=(10,8))
sns.jointplot(data = pippali_data, x = "Concentration_mg_g", y = "Bioactivity_Score", kind = "reg")
plt.title("Concentration vs Bioactivity Score")
sns.despine()
plt.show()

# 2.2 Feature Correlation Matrix
plt.figure(figsize=(10,9))
pippali_corr = pippali_data.corr(numeric_only=True)
sns.heatmap(data = pippali_corr, annot = True, cmap = "YlGnBu")
plt.title("Phytochemical Feature Correlations")
sns.despine()
plt.show()

# ==========================================
# SECTION 3: MORPHOLOGICAL & COMPARATIVE ASSAYS
# ==========================================

# 3.1 Species Variance (Iris Dataset as Proxy for Morphological Data)
iris = sns.load_dataset("iris")
plt.figure(figsize=(10,9))
sns.boxplot(data = iris, x = "species", y = "petal_length")
plt.title("Boxplot of Petal Length by Species")
sns.despine()
plt.show()

# 3.2 Multi-Panel Research Summary (Subplots)
plt.figure(figsize=(10,8))
plt.subplot(1,2,1)
sns.barplot(data = pippali_data, x = "Concentration_mg_g", y = "Phytochemical", hue = "Solubility_Index", palette = "mako")
plt.title("Concentration of Different Phytochemicals")
plt.subplot(1,2,2)
sns.scatterplot(data = pippali_data, x = "Concentration_mg_g", y = "Bioactivity_Score")
plt.title("Concentration vs Bioactivity Score")
plt.tight_layout()
sns.despine()
plt.show()