# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BskOo6jo8fNIR9o_HYsq2klPvDcwOcNM
"""

"""
INFLAMMATORY GENE PROFILING & SOLVENT EFFICIENCY - DAY 17
Focus: Multivariate Distributions (Jointplots), Solvent Inhibition Variance (Boxplots), and Pivot-Heatmapping
Project: Comparative Efficacy of Piper longum and Adhatoda vasica on Pro-inflammatory Targets
"""
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

np.random.seed(42)
# ==========================================
# SECTION 1: BIO-ANALYTICAL DATASET GENERATION
# ==========================================

# Research Data: Measuring inflammatory marker response to polyherbal extracts
data = {
    'Gene_Target': np.random.choice(['IL-6', 'TNF-alpha', 'COX-2', 'IL-1beta', 'NF-kB'], 100),
    'Expression_Level': np.random.normal(50, 15, 100),
    'Plant_Extract': np.random.choice(['Piper longum', 'Adhatoda vasica', 'Control'], 100),
    'Extraction_Solvent': np.random.choice(['Methanolic', 'Aqueous', 'Ethanolic'], 100),
    'Inhibition_Rate': np.random.uniform(0, 100, 100)
}
df_bio = pd.DataFrame(data)

# ==========================================
# SECTION 2: TARGET DISTRIBUTION & VARIANCE
# ==========================================

# 2.1 Comparative Sample Density: Gene targets per plant extract
plt.figure(figsize=(10,8))
sns.countplot(data= df_bio, x = "Gene_Target", hue = "Plant_Extract")
plt.title("Distribution of Genes Across Plants")
sns.despine()
plt.show()

# 2.2 Solvent Potency Variance: Boxplot analysis of inhibition rates
# Standard professional visualization for showing Median and Interquartile Range (IQR)
plt.figure(figsize=(10,9))
sns.boxplot(data = df_bio, x ="Extraction_Solvent", y = "Inhibition_Rate")
plt.title("Inhibition Rate by Extraction Solvent")
sns.despine()
plt.show()

# ==========================================
# SECTION 3: EXPRESSION KINETICS
# ==========================================

# 3.1 Expression Density: Histograms with Kernel Density Estimation (KDE)
plt.figure(figsize=(10,9))
sns.histplot(data = df_bio, x = "Expression_Level", hue = "Plant_Extract", kde = True, palette = "magma")
plt.title("Distribution of Gene Expression Levels")
sns.despine()
plt.show()

# 3.2 Correlation Mapping: Expression Level vs. Inhibition Rate
plt.figure(figsize=(10,9))
sns.scatterplot(data = df_bio, x = "Expression_Level", y = "Inhibition_Rate", hue = "Plant_Extract", palette = "viridis")
plt.title("Gene Expression vs. Inhibition Rate")
sns.despine()
plt.show()

# 3.3 Multivariate Marginal Analysis: Jointplot for Density & Correlation
# Combining scatter plots with marginal histograms for total distribution context
plt.figure(figsize=(10,9))
sns.jointplot(data = df_bio, x = "Expression_Level", y = "Inhibition_Rate", color = "purple")
plt.title("Gene Expression vs. Inhibition Rate")
sns.despine()
plt.show()

# ==========================================
# SECTION 4: DATA RESHAPING & HEATMAP PIVOT
# ==========================================

# 4.1 Pivot Table Construction: Averaging Inhibition per Target/Extract
# Reshaping long-form data into a wide-form matrix for visualization
df_matrix = df_bio.pivot_table(index='Gene_Target',
                                columns='Plant_Extract',
                                values='Inhibition_Rate')
plt.figure(figsize=(10,8))
sns.heatmap(data = df_matrix, annot = True, cmap = "YlGnBu")
plt.title("Clustered gene expression")
sns.despine()
plt.show()