# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOI2bosP-GYDHUl8WV4knibF_ZLtUAop
"""

"""
PHYTOCHEMICAL EXTRACTION OPTIMIZATION - DAY 10
Focus: Solvent Efficacy, Antioxidant Profiling, and Bioavailability Correlation
Project: Piper longum (Pippali) Secondary Metabolite Analysis
"""
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

np.random.seed(101)
# ==========================================
# SECTION 1: RESEARCH DATASET GENERATION
# ==========================================

# Simulating a 25-compound extraction assay with 5 different solvents
data = {
    'Compound_ID': [f'CPD_{i:02d}' for i in range(1, 26)],
    'Solvent': np.random.choice(['Ethanol', 'Methanol', 'Water', 'Ethyl Acetate', 'Hexane'], 25),
    'Antioxidant_Activity': np.random.uniform(10, 95, 25),
    'Bioavailability_Score': np.random.uniform(0.1, 0.9, 25),
    'Molecular_Weight': np.random.uniform(150, 500, 25),
    'Yield_mg_g': np.random.uniform(5, 50, 25)
}
df_phytochem = pd.DataFrame(data)

# ==========================================
# SECTION 2: POTENCY & YIELD ANALYSIS
# ==========================================

# 2.1 Ranked Potency: Antioxidant Activity by Compound
plt.figure(figsize=(10,8))
sns.barplot(data = df_phytochem, x = "Antioxidant_Activity", y = "Compound_ID")
plt.title("ranking of compounds by antioxidant activity")
sns.despine()
plt.show()

# ==========================================
# SECTION 3: PHYSIOCHEMICAL CORRELATIONS
# ==========================================

# 3.1 Yield Dynamics: Influence of Molecular Weight
plt.figure(figsize=(10,8))
sns.scatterplot(data = df_phytochem, x = "Molecular_Weight", y ="Yield_mg_g")
plt.title("Comparison of molecular weight to the Yield")
sns.despine()
plt.show()

# 3.2 Distribution Analysis: Molecular Weight Spread
plt.figure(figsize=(10,8))
sns.histplot(data = df_phytochem, x = "Molecular_Weight", bins = 10, kde = True , color = "teal")
plt.title("Distribution of molecular weights")
sns.despine()
plt.show()

#Extraction Efficacy: Solvent vs. Yield
plt.figure(figsize=(10,8))
sns.barplot(data = df_phytochem, x = "Solvent", y = "Yield_mg_g", palette = "magma")
plt.title("Solvent vs Highest Yeild")
sns.despine()
plt.show()

# Therapeutic Window: Bioavailability vs. Antioxidant Activity
plt.figure(figsize=(10,9))
sns.scatterplot(data = df_phytochem, x = "Antioxidant_Activity", y = "Bioavailability_Score", hue = "Solvent", palette = "bright")
plt.title("Bioavailability vs antioxidant activity")
sns.despine()
plt.show()

#  Joint Distribution: structural Impact on Potency
# Professional jointplot to see both individual and combined distributions
plt.figure(figsize=(10,9))
sns.jointplot(data = df_phytochem, x = "Molecular_Weight", y = "Antioxidant_Activity", color = "olive")
plt.title("Molecular Weight vs antioxidant activity")
sns.despine()
plt.show()